### ISSUE TITLE
is WaveletReconstruction implemented complete yet?

### ISSUE THREAD

**Issue by chuchong** [daviddoria/WaveletReconstruction#1]
Hello, I am also interests in the reimplementation of the wavelet reconstruction method. So I wonder if this implementation is complete yet? Since there's an error when compiling and I find `pipeline` is not initilized somewhere. And there seems no lines using input data in 'vtkWaveletReconstruction.cxx'
```
WaveletReconstruction/vtkWaveletReconstruction.cxx:175:11: error: ‘pipeline’ was not declared in this scope
  175 |   while (!pipeline[pipeline.size()-1].finished)
      |           ^~~~~~~~
```
Thank you!

**Comment by daviddoria** [comment]
Hi chuchong,

Unfortunately this was a long, long time ago. Feel free to use the code if it's useful, but unfortunately I won't be able to support it.

Good luck!

**Comment by chuchong** [comment]
Thanks
